<?php
// database/seeders/RoleSeeder.php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;
use App\Models\Role;
use Illuminate\Support\Carbon;

class FilmSeeder extends Seeder
{
    public function run()
    {

        Film::truncate(); // Удалит все записи и сбросит счетчик ID

        $films = [
            [
                'id' => 1,
                'name' => 'Midnight Special',
                'preview_image' => 'http://localhost:3000/img/midnight-special.jpg',
                'background_image' => 'http://localhost:3000/img/midnight-special.jpg',
                'background_color' => '#828585',
                'video_link' => 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
                'preview_video_link' => 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
                'rating' => 3.3,
                'scores_count' => 67815,
                'director' => 'Jeff Nichols',
                'starring' => '["Michael Shannon","Joel Edgerton","Kirsten Dunst"]',
                'run_time' => 112,
                'genre' => 'Action',
                'released' => 2016,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'name' => 'A Star Is Born',
                'preview_image' => 'http://localhost:3000/img/dardjeeling-limited.jpg',
                'background_image' => 'http://localhost:3000/img/dardjeeling-limited.jpg',
                'background_color' => '#C4C0C0',
                'video_link' => 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
                'preview_video_link' => 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
                'rating' => 3.9,
                'scores_count' => 244484,
                'director' => 'Bradley Cooper',
                'starring' => '["Lady Gaga","Bradley Cooper","Sam Elliott"]',
                'run_time' => 136,
                'genre' => 'Drama',
                'released' => 2018,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'snatch',
                'preview_image' => 'http://localhost:3000/img/snatch.jpg',
                'background_image' => 'http://localhost:3000/img/snatch.jpg',
                'background_color' => '#FDFDFC',
                'video_link' => 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
                'preview_video_link' => 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
                'rating' => 0.2,
                'scores_count' => 716577,
                'director' => 'Guy Ritchie',
                'starring' => '["Jason Statham","Brad Pitt","Benicio Del Toro"]',
                'run_time' => 104,
                'genre' => 'Comedy',
                'released' => 2000,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'What We Do in the Shadows',
                'preview_image' => 'http://localhost:3000/img/what-we-do-in-the-shadows.jpg',
                'background_image' => 'http://localhost:3000/img/what-we-do-in-the-shadows.jpg',
                'background_color' => '#A39E81',
                'video_link' => 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
                'preview_video_link' => 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
                'rating' => 7.2,
                'scores_count' => 6173,
                'director' => 'Jemaine Clement',
                'starring' => '["Kayvan Novak","Matt Berry","Natasia Demetriou"]',
                'run_time' => 30,
                'genre' => 'Comedy',
                'released' => 2019,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'Orlando',
                'preview_image' => 'http://localhost:3000/img/orlando.jpg',
                'background_image' => 'http://localhost:3000/img/orlando.jpg',
                'background_color' => '#D8D3BD',
                'video_link' => 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
                'preview_video_link' => 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
                'rating' => 2.6,
                'scores_count' => 12292,
                'director' => 'Sally Potter',
                'starring' => '["Tilda Swinton","Billy Zane","Quentin Crisp"]',
                'run_time' => 94,
                'genre' => 'Drama',
                'released' => 1992,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'Macbeth',
                'preview_image' => 'http://localhost:3000/img/macbeth.jpg',
                'background_image' => 'http://localhost:3000/img/macbeth.jpg',
                'background_color' => '#F1E9CE',
                'video_link' => 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
                'preview_video_link' => 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
                'rating' => 3.3,
                'scores_count' => 48798,
                'director' => 'Justin Kurzel',
                'starring' => '["Michael Fassbender","Marion Cotillard","Jack Madigan"]',
                'run_time' => 113,
                'genre' => 'Drama',
                'released' => 2015,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'name' => 'Bohemian Rhapsody',
                'preview_image' => 'http://localhost:3000/img/bohemian-rhapsody.jpg',
                'background_image' => 'http://localhost:3000/img/bohemian-rhapsody.jpg',
                'background_color' => '#929FA5',
                'video_link' => 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
                'preview_video_link' => 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
                'rating' => 6.1,
                'scores_count' => 338903,
                'director' => 'Bryan Singer',
                'starring' => '["Rami Malek","Lucy Boynton","Gwilym Lee"]',
                'run_time' => 134,
                'genre' => 'Drama',
                'released' => 2018,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'name' => 'War of the Worlds',
                'preview_image' => 'http://localhost:3000/img/war-of-the-worlds.jpg',
                'background_image' => 'http://localhost:3000/img/war-of-the-worlds.jpg',
                'background_color' => '#9B7E61',
                'video_link' => 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
                'preview_video_link' => 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
                'rating' => 9.3,
                'scores_count' => 386834,
                'director' => 'Steven Spielberg',
                'starring' => '["Tom Cruise","Dakota Fanning","Tim Robbins"]',
                'run_time' => 116,
                'genre' => 'Adventure',
                'released' => 2005,
                'is_favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        Film::insert($films);
    }
}
