version: '3.8'

services:
  web:
    container_name: web
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"

  api:
    container_name: api
    image: php:8.4-cli
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y libpq-dev git unzip &&
      docker-php-ext-install pdo_pgsql pgsql &&
      curl -sS https://getcomposer.org/installer | php &&
      mv composer.phar /usr/local/bin/composer &&
      composer install &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  node_modules:
  pgdata:
